# Generated by Django 4.2.2 on 2023-07-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_attendance_id_attendance_att_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='att_id',
            new_name='id',
        ),
    ]
